services:
  - type: web
    name: company-enrichment-api
    env: docker
    region: oregon
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SERPAPI_KEY
        sync: false
      - key: BING_SEARCH_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: FLARESOLVERR_URL
        value: http://localhost:8191/v1
